---
apiVersion: v1
kind: Namespace
metadata:
  name: sshare

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sshare
  namespace: sshare

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sshare-server
  name: sshare-server
  namespace: sshare
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: sshare-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: sshare-server
    spec:
      containers:
      - args:
        - --in-cluster
        - --namespace=sshare
        - --backend-domain=sshare.mydomain.com
        - --backend-https-enabled
        - --tls-ca=/etc/tls/ca.pem
        - --tls-key=/etc/tls/key.pem
        - --tls-cert=/etc/tls/cert.pem
        - --tls-enabled
        image: tczekajlo/sshare:1.0.0
        imagePullPolicy: Always
        name: sshare-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls
          name: tls
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sshare
      serviceAccountName: sshare
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls
        secret:
          defaultMode: 420
          secretName: tls

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: sshare-server
  name: sshare-server
  namespace: sshare
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: plain
    port: 50041
    protocol: TCP
    targetPort: 50041
  - name: tls
    port: 50040
    protocol: TCP
    targetPort: 50040
  selector:
    run: sshare-server
  sessionAffinity: None
  type: LoadBalancer

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-cluster
  namespace: sshare
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: sshare
  namespace: sshare